import type { Question, LanguageCode } from '../types';

/** Demo: Türkçe arayüz / dil seçimi TR iken kullanılan 10 soru. */
export const MOCK_DEMO_QUESTIONS_TR: Question[] = [
  {
    id: 'demo-tr-1',
    text: '55 yaşında erkek hasta, ani başlayan şiddetli göğüs ağrısı ile başvuruyor. EKG’de V1–V4 derivasyonlarında ST elevasyonu var. En olası etkilenen koroner arter hangisidir?',
    options: ['Sağ koroner arter (RCA)', 'Sol ön inen arter (LAD)', 'Sirkumfleks arter (Cx)', 'Sol ana koroner arter (LMCA)', 'Posterior inen arter (PDA)'],
    correctAnswerIndex: 1,
    explanation: 'V1–V4 anterior duvarı gösterir; bu bölgenin ana besleyicisi LAD’dır.',
    sourceQuote: 'Anterior MI tablosunda ST elevasyonu genellikle LAD tıkanıklığı ile ilişkilidir.',
  },
  {
    id: 'demo-tr-2',
    text: 'Tip 2 diyabette çoğu kılavuzda yetişkinler için bireyselleştirilmiş HbA1c hedefi genellikle hangi aralığa yakındır?',
    options: ['%3–4 (her zaman)', '%7 civarı — risk ve komorbiditeye göre ayarlanır', '%10 üzeri ideal', 'Sadece açlık glukozu yeterli', 'HbA1c ölçülmez'],
    correctAnswerIndex: 1,
    explanation: 'HbA1c hedefi bireye göre değişir; çoğu yetişkin için %7 altı veya yakını önerilir.',
    sourceQuote: '',
  },
  {
    id: 'demo-tr-3',
    text: 'Komorbiditesi olmayan hipertansiyonda ilk basamakta sık başvurulan ilaç gruplarından hangisi en uygun genel ifadedir?',
    options: ['Sadece loop diüretik', 'ACE inhibitörü/ARB, tiyazid veya kalsiyum kanal blokeri (kılavuza göre)', 'Dijital', 'Nitrat tek başına', 'Sistemik steroid'],
    correctAnswerIndex: 1,
    explanation: 'İlk basamakta genelde ACEi/ARB, tiyaz benzeri veya DHP-CCB seçenekleri öne çıkar.',
    sourceQuote: '',
  },
  {
    id: 'demo-tr-4',
    text: 'Toplum kökenli pnömonide ciddiyet riskini tarayan CURB-65 skorunda “U” neyi temsil eder?',
    options: ['Ürik asit', 'Üre (BUN)', 'Ürobilinogen', 'Üst solunum kültürü', 'Üveit'],
    correctAnswerIndex: 1,
    explanation: 'CURB-65: Konfüzyon, Üre, Solunum sayısı, Kan basıncı, 65 yaş.',
    sourceQuote: '',
  },
  {
    id: 'demo-tr-5',
    text: 'Mikrositik anemi düşünülen hastada ilk ayırıcı tetkik yaklaşımı hangisidir?',
    options: ['Direkt Coombs', 'Serum demir, ferritin, TDBK', 'Kemik iliği biyopsisi her zaman', 'Sadece B12', 'Sadece folat'],
    correctAnswerIndex: 1,
    explanation: 'Mikrositik tabloda demir metabolizması ve kronik hastalık ayırımı temeldir.',
    sourceQuote: '',
  },
  {
    id: 'demo-tr-6',
    text: 'Akut böbrek hasarı (AKI) tanısında kullanılan evreleme sistemlerinden biri hangisidir?',
    options: ['CHADS2', 'RIFLE / KDIGO', 'Wells', 'CURB-65', 'APGAR'],
    correctAnswerIndex: 1,
    explanation: 'AKI için KDIGO kriterleri ve RIFLE evrelemesi yaygın kullanılır.',
    sourceQuote: '',
  },
  {
    id: 'demo-tr-7',
    text: 'İskemik inmede intravenöz tromboliz için tipik zaman penceresi (son bilinen iyi durumdan itibaren) çoğu protokolde yaklaşık kaç saattir?',
    options: ['1 saat', '3 saat', '4,5 saat', '24 saat', '72 saat'],
    correctAnswerIndex: 2,
    explanation: 'tPA için yaygın üst sınır son bilinen iyi durumdan itibaren ~4,5 saattir (ekclusionlar hariç).',
    sourceQuote: '',
  },
  {
    id: 'demo-tr-8',
    text: 'Akut astım atağında ilk hatada sık kullanılan inhale bronkodilatör sınıfı hangisidir?',
    options: ['Beta-2 agonistler (ör. salbutamol)', 'Sadece sisteminik steroid tek başına inhale', 'Opioid', 'Topikal antifungal', 'Muskarinik agonistler'],
    correctAnswerIndex: 0,
    explanation: 'Kısa etkili beta-2 agonist nebül veya MDI ile inhale ilk basamaktır.',
    sourceQuote: '',
  },
  {
    id: 'demo-tr-9',
    text: 'Primer hipotiroidide tipik olarak hangi laboratuvar bulgusu beklenir?',
    options: ['Düşük TSH, yüksek T4', 'Yüksek TSH, düşük serbest T4', 'Yüksek TSH, yüksek T4', 'Normal TSH, yükselmiş kortizol', 'Sadece yükselmiş ferritin'],
    correctAnswerIndex: 1,
    explanation: 'Primer hipotiroidide TSH yükselir, serbest T4 düşük olabilir.',
    sourceQuote: '',
  },
  {
    id: 'demo-tr-10',
    text: 'Alt ekstremite DVT ön-test olasılığını değerlendirmede kullanılan skorlardan biri hangisidir?',
    options: ['CHA₂DS₂-VASc', 'Wells (DVT)', 'Glasgow', 'APGAR', 'NIHSS'],
    correctAnswerIndex: 1,
    explanation: 'DVT için Wells klinik olasılık skoru yaygın kullanılır.',
    sourceQuote: '',
  },
];

/** Demo: English UI / dil seçimi EN iken kullanılan 10 soru. */
export const MOCK_DEMO_QUESTIONS_EN: Question[] = [
  {
    id: 'demo-en-1',
    text: 'A 62-year-old woman with fever and dysuria has pyuria on urinalysis. Which finding best supports a diagnosis of acute bacterial cystitis rather than contamination?',
    options: ['Squamous epithelial cells dominating', 'Many nitrite-positive leukocyte esterase with bacteria', 'Only hyaline casts', 'pH 5.0 alone', 'Absence of any WBCs'],
    correctAnswerIndex: 1,
    explanation: 'Nitrite and leukocyte esterase positivity with bacteriuria supports infection.',
    sourceQuote: '',
  },
  {
    id: 'demo-en-2',
    text: 'Which ECG finding is most characteristic of acute pericarditis in the appropriate clinical context?',
    options: ['Pathologic Q waves in III and aVF', 'Diffuse ST-segment elevation with PR depression', 'Left axis deviation only', 'Peaked T waves in V1–V2 only', 'Epsilon waves'],
    correctAnswerIndex: 1,
    explanation: 'Diffuse ST elevation with PR depression suggests pericarditis.',
    sourceQuote: '',
  },
  {
    id: 'demo-en-3',
    text: 'First-line pharmacotherapy for generalized anxiety disorder commonly includes which class?',
    options: ['Typical antipsychotics only', 'SSRI or SNRI', 'Chronic benzodiazepine monotherapy', 'Digoxin', 'Loop diuretics'],
    correctAnswerIndex: 1,
    explanation: 'SSRIs/SNRIs are guideline-supported first-line options for GAD.',
    sourceQuote: '',
  },
  {
    id: 'demo-en-4',
    text: 'A patient with cirrhosis presents with confusion and asterixis. Which laboratory pair is most helpful initially to evaluate suspected hepatic encephalopathy?',
    options: ['Troponin and CK-MB', 'Ammonia (interpreted in clinical context) with metabolic panel', 'PSA only', 'TSH alone', 'LDH isoenzymes only'],
    correctAnswerIndex: 1,
    explanation: 'Ammonia can support HE but must be interpreted clinically; metabolic derangements are assessed.',
    sourceQuote: '',
  },
  {
    id: 'demo-en-5',
    text: 'Which organism is the most common bacterial cause of community-acquired pneumonia overall in many adult series?',
    options: ['Mycobacterium tuberculosis', 'Streptococcus pneumoniae', 'Histoplasma capsulatum', 'Aspergillus fumigatus', 'Clostridioides difficile'],
    correctAnswerIndex: 1,
    explanation: 'Streptococcus pneumoniae remains a leading bacterial CAP pathogen.',
    sourceQuote: '',
  },
  {
    id: 'demo-en-6',
    text: 'Iron deficiency anemia is most commonly caused by which problem in premenopausal women?',
    options: ['Hemolysis from G6PD deficiency', 'Chronic blood loss (e.g., menorrhagia)', 'Vitamin B12 malabsorption only', 'Chronic lymphocytic leukemia only', 'Hyperthyroidism'],
    correctAnswerIndex: 1,
    explanation: 'Menstrual blood loss is a frequent cause of iron deficiency in younger women.',
    sourceQuote: '',
  },
  {
    id: 'demo-en-7',
    text: 'Which test is most appropriate to screen for latent tuberculosis infection in an asymptomatic adult before initiating anti-TNF therapy?',
    options: ['Chest X-ray alone', 'IGRA or TST per guideline', 'Blood culture', 'Urinalysis', 'EEG'],
    correctAnswerIndex: 1,
    explanation: 'IGRA or TST is used for LTBI screening depending on local guidance.',
    sourceQuote: '',
  },
  {
    id: 'demo-en-8',
    text: 'Classic triad of pheochromocytoma may include headache, sweating, and:',
    options: ['Bradycardia', 'Palpitations / tachycardia', 'Jaundice', 'Hematuria', 'Ptosis'],
    correctAnswerIndex: 1,
    explanation: 'Episodic hypertension with headache, sweating, and palpitations is classic.',
    sourceQuote: '',
  },
  {
    id: 'demo-en-9',
    text: 'Which feature best differentiates ulcerative colitis from Crohn disease in many cases?',
    options: ['UC: transmural skip lesions throughout mouth to anus', 'UC: continuous colonic inflammation starting rectally; Crohn: skip lesions anywhere in GI tract', 'Crohn: only rectal involvement', 'Both are always limited to ileum', 'Neither causes extraintestinal manifestations'],
    correctAnswerIndex: 1,
    explanation: 'UC is continuous from rectum; Crohn can have skip lesions and transmural inflammation.',
    sourceQuote: '',
  },
  {
    id: 'demo-en-10',
    text: 'In anaphylaxis, intramuscular epinephrine is typically administered into which site?',
    options: ['Intravenous only without monitoring', 'Mid-anterolateral thigh', 'Subcutaneous abdomen only', 'Dorsum of foot', 'Sublingual'],
    correctAnswerIndex: 1,
    explanation: 'IM epinephrine is given in the mid-anterolateral thigh for rapid absorption.',
    sourceQuote: '',
  },
];

export function getDemoQuestionPool(language: LanguageCode): Question[] {
  return language === 'tr' ? MOCK_DEMO_QUESTIONS_TR : MOCK_DEMO_QUESTIONS_EN;
}
