import type { LanguageCode, Question } from '../types';

export const MOCK_DEMO_QUESTIONS_TR: Question[] = [
  {
    id: 'demo-tr-1',
    text: '68 yaşında erkek hasta ani başlayan göğüs ağrısıyla başvuruyor. EKG’de II, III ve aVF derivasyonlarında ST elevasyonu saptanıyor. Bu tablo en çok hangi miyokard enfarktüsü lokalizasyonunu düşündürür?',
    options: ['Anterior MI', 'İnferior MI', 'Lateral MI', 'Septal MI', 'Posterior MI'],
    correctAnswerIndex: 1,
    explanation: 'II, III ve aVF inferior duvarı temsil eder. Bu derivasyonlardaki ST elevasyonu inferior MI ile uyumludur.',
    sourceQuote: 'II, III ve aVF derivasyonlarındaki ST elevasyonu inferior duvar iskemisini düşündürür.',
  },
  {
    id: 'demo-tr-2',
    text: 'Tip 1 diyabetli hastada poliüri, polidipsi, karın ağrısı ve Kussmaul solunumu gelişiyor. En olası tanı hangisidir?',
    options: ['Hipoglisemi', 'Diyabetik ketoasidoz', 'Hiperosmolar hiperglisemik durum', 'Laktik asidoz', 'Akut pankreatit'],
    correctAnswerIndex: 1,
    explanation: 'Kussmaul solunumu, karın ağrısı ve dehidratasyon bulguları tipik olarak diyabetik ketoasidozu düşündürür.',
    sourceQuote: 'Ketoasidozda derin ve hızlı solunum ile metabolik asidoz bulguları görülebilir.',
  },
  {
    id: 'demo-tr-3',
    text: 'Ateş, öksürük ve balgam yakınması olan hastada akciğer grafisinde sağ alt lob infiltrasyonu görülüyor. Toplum kökenli pnömonide en sık etken hangisidir?',
    options: ['Streptococcus pneumoniae', 'Mycobacterium tuberculosis', 'Pseudomonas aeruginosa', 'Candida albicans', 'Legionella her zaman ilk sıradadır'],
    correctAnswerIndex: 0,
    explanation: 'Toplum kökenli pnömonide en sık klasik etken Streptococcus pneumoniae kabul edilir.',
    sourceQuote: 'Toplum kökenli pnömoninin en sık bakteriyel etkeni pnömokoktur.',
  },
  {
    id: 'demo-tr-4',
    text: 'Hipertansiyon değerlendirmesinde hedef organ hasarı açısından aşağıdakilerden hangisi tipik bir bulgu değildir?',
    options: ['Sol ventrikül hipertrofisi', 'Hipertansif retinopati', 'Proteinüri', 'Akut apandisit', 'Kronik böbrek hasarı'],
    correctAnswerIndex: 3,
    explanation: 'Akut apandisit hipertansiyonun hedef organ hasarı değildir. Diğer seçenekler kronik hipertansiyonla ilişkilidir.',
    sourceQuote: 'Hipertansiyonda kalp, böbrek, retina ve beyin hedef organ olarak etkilenebilir.',
  },
  {
    id: 'demo-tr-5',
    text: 'Mikrositik hipokrom anemi saptanan hastada demir eksikliği anemisini destekleyen laboratuvar kombinasyonu hangisidir?',
    options: ['Yüksek ferritin, düşük TDBK', 'Düşük ferritin, yüksek TDBK', 'Yüksek B12, düşük folat', 'Yüksek retikülosit, yüksek bilirubin', 'Düşük TSH, yüksek serbest T4'],
    correctAnswerIndex: 1,
    explanation: 'Demir eksikliğinde ferritin düşer, total demir bağlama kapasitesi yükselir.',
    sourceQuote: 'Demir eksikliği anemisinde ferritin düşük ve TDBK yüksek bulunur.',
  },
  {
    id: 'demo-tr-6',
    text: 'Astım atağı ile gelen hastada acil serviste ilk basamak inhaler tedavi olarak en sık hangisi tercih edilir?',
    options: ['Kısa etkili beta-2 agonist', 'Uzun etkili beta-2 agonist tek başına', 'İnhale antibiyotik', 'Mukolitik şurup', 'Antihistaminik krem'],
    correctAnswerIndex: 0,
    explanation: 'Akut astım atağında hızlı bronkodilatasyon için kısa etkili beta-2 agonistler ilk tercihtir.',
    sourceQuote: 'Akut bronkospazm tedavisinde kısa etkili beta-2 agonistler ön plandadır.',
  },
  {
    id: 'demo-tr-7',
    text: 'Primer hipotiroidisi olan hastada beklenen laboratuvar profili hangisidir?',
    options: ['Düşük TSH, yüksek serbest T4', 'Yüksek TSH, düşük serbest T4', 'Düşük TSH, düşük kortizol', 'Yüksek TSH, yüksek büyüme hormonu', 'Normal TSH, yüksek troponin'],
    correctAnswerIndex: 1,
    explanation: 'Primer hipotiroidide tiroid hormon üretimi azaldığı için serbest T4 düşer, TSH kompansatuvar olarak yükselir.',
    sourceQuote: 'Primer hipotiroidide tipik olarak TSH yüksek, serbest T4 düşük saptanır.',
  },
  {
    id: 'demo-tr-8',
    text: 'Alt ekstremitede şişlik ve ağrı ile gelen hastada derin ven trombozu ön test olasılığını değerlendirmede hangi skor kullanılır?',
    options: ['CHA2DS2-VASc', 'Wells skoru', 'Glasgow koma skoru', 'APGAR skoru', 'Child-Pugh skoru'],
    correctAnswerIndex: 1,
    explanation: 'DVT klinik olasılığının değerlendirilmesinde Wells skoru yaygın olarak kullanılır.',
    sourceQuote: 'Wells skoru, derin ven trombozu olasılığını değerlendirmede yardımcıdır.',
  },
  {
    id: 'demo-tr-9',
    text: 'Ani gelişen nörolojik defisit ile gelen hastada iskemik inme düşünülüyor. Uygun hastalarda intravenöz tromboliz için klasik üst zaman penceresi yaklaşık kaç saattir?',
    options: ['1 saat', '2 saat', '4,5 saat', '12 saat', '24 saat'],
    correctAnswerIndex: 2,
    explanation: 'Seçilmiş uygun hastalarda intravenöz tromboliz için yaygın kabul gören üst sınır yaklaşık 4,5 saattir.',
    sourceQuote: 'İskemik inmede trombolitik tedavi için zaman penceresi sınırlıdır ve erken başvuru önemlidir.',
  },
  {
    id: 'demo-tr-10',
    text: 'Sirozlu hastada konfüzyon ve asteriksis gelişiyor. Bu tablo en çok hangi komplikasyonu düşündürür?',
    options: ['Hepatik ensefalopati', 'Akut glokom', 'Menenjit', 'Hipertiroidi', 'Akut otitis media'],
    correctAnswerIndex: 0,
    explanation: 'Sirozlu hastada bilinç değişikliği ve asteriksis hepatik ensefalopatinin klasik bulgularındandır.',
    sourceQuote: 'Asteriksis ve mental durum değişikliği hepatik ensefalopati ile ilişkili olabilir.',
  },
];

export const MOCK_DEMO_QUESTIONS_EN: Question[] = [
  {
    id: 'demo-en-1',
    text: 'A patient presents with crushing chest pain and ST-segment elevation in leads V1 through V4. Which coronary artery is most likely involved?',
    options: ['Right coronary artery', 'Left anterior descending artery', 'Left circumflex artery', 'Posterior descending artery', 'Obtuse marginal artery'],
    correctAnswerIndex: 1,
    explanation: 'Leads V1 through V4 reflect the anterior wall, which is classically supplied by the LAD.',
    sourceQuote: 'Anterior ST elevation usually points to left anterior descending artery occlusion.',
  },
  {
    id: 'demo-en-2',
    text: 'Which acid-base disorder is most characteristic of diabetic ketoacidosis?',
    options: ['Metabolic alkalosis', 'Respiratory alkalosis', 'High anion gap metabolic acidosis', 'Non-anion gap metabolic acidosis only', 'Respiratory acidosis'],
    correctAnswerIndex: 2,
    explanation: 'DKA causes ketoacid accumulation, leading to a high anion gap metabolic acidosis.',
    sourceQuote: 'Ketoacid production in DKA leads to high anion gap metabolic acidosis.',
  },
  {
    id: 'demo-en-3',
    text: 'What is the most common bacterial cause of community-acquired pneumonia in adults?',
    options: ['Streptococcus pneumoniae', 'Pseudomonas aeruginosa', 'Staphylococcus epidermidis', 'Candida albicans', 'Clostridioides difficile'],
    correctAnswerIndex: 0,
    explanation: 'Streptococcus pneumoniae remains the classic most common bacterial cause of CAP.',
    sourceQuote: 'Pneumococcus is a leading pathogen in community-acquired pneumonia.',
  },
  {
    id: 'demo-en-4',
    text: 'Which medication class is commonly used first-line for acute relief during an asthma exacerbation?',
    options: ['Short-acting beta-2 agonists', 'Proton pump inhibitors', 'Long-acting nitrates', 'Loop diuretics', 'Topical corticosteroids only'],
    correctAnswerIndex: 0,
    explanation: 'Short-acting beta-2 agonists provide rapid bronchodilation and are first-line rescue therapy.',
    sourceQuote: 'Rapid-acting inhaled bronchodilators are central in acute asthma treatment.',
  },
  {
    id: 'demo-en-5',
    text: 'Which laboratory pattern best fits primary hypothyroidism?',
    options: ['Low TSH and high free T4', 'High TSH and low free T4', 'Low TSH and low cortisol', 'High TSH and high free T4 always', 'Normal TSH and elevated troponin'],
    correctAnswerIndex: 1,
    explanation: 'In primary thyroid gland failure, TSH rises while free T4 falls.',
    sourceQuote: 'Primary hypothyroidism is typically associated with elevated TSH and reduced free T4.',
  },
  {
    id: 'demo-en-6',
    text: 'A patient with unilateral leg swelling and pain is being assessed for deep vein thrombosis. Which clinical score is commonly used for pretest probability?',
    options: ['Glasgow Coma Scale', 'Wells score', 'APGAR score', 'MELD score', 'Bishop score'],
    correctAnswerIndex: 1,
    explanation: 'The Wells score is widely used to estimate clinical probability for DVT.',
    sourceQuote: 'The Wells score helps stratify suspected deep vein thrombosis risk.',
  },
  {
    id: 'demo-en-7',
    text: 'In eligible ischemic stroke patients, intravenous thrombolysis is generally considered within what approximate time window from last known well?',
    options: ['30 minutes', '2 hours', '4.5 hours', '10 hours', '24 hours'],
    correctAnswerIndex: 2,
    explanation: 'The commonly cited upper limit for IV thrombolysis in selected patients is about 4.5 hours.',
    sourceQuote: 'Acute ischemic stroke treatment is highly time dependent, with a limited thrombolysis window.',
  },
  {
    id: 'demo-en-8',
    text: 'Which finding is most typical of iron deficiency anemia?',
    options: ['Low ferritin and high total iron-binding capacity', 'High ferritin and low TIBC', 'Elevated vitamin B12', 'High reticulocyte count from hemolysis', 'Low ESR as the defining feature'],
    correctAnswerIndex: 0,
    explanation: 'Iron deficiency anemia usually shows depleted iron stores with low ferritin and increased TIBC.',
    sourceQuote: 'Iron deficiency is characterized by reduced ferritin and increased iron-binding capacity.',
  },
  {
    id: 'demo-en-9',
    text: 'A cirrhotic patient develops confusion and asterixis. Which complication is most likely?',
    options: ['Hepatic encephalopathy', 'Acute otitis externa', 'Hyperthyroidism', 'Pulmonary embolism by definition', 'Migraine aura'],
    correctAnswerIndex: 0,
    explanation: 'Confusion plus asterixis in cirrhosis strongly suggests hepatic encephalopathy.',
    sourceQuote: 'Asterixis and altered mentation are classic clues to hepatic encephalopathy.',
  },
  {
    id: 'demo-en-10',
    text: 'Diffuse ST-segment elevation with PR depression on ECG is most characteristic of which condition?',
    options: ['Acute pericarditis', 'Inferior myocardial infarction', 'Pulmonary embolism', 'Hyperkalemia only', 'Second-degree AV block'],
    correctAnswerIndex: 0,
    explanation: 'Diffuse ST elevation with PR depression is a classic ECG pattern of acute pericarditis.',
    sourceQuote: 'Pericarditis commonly produces widespread ST elevation and PR-segment depression.',
  },
];

export function getDemoQuestionPool(language: LanguageCode): Question[] {
  return language === 'tr' ? MOCK_DEMO_QUESTIONS_TR : MOCK_DEMO_QUESTIONS_EN;
}
