import type { LanguageCode } from '../../../types';

export const PDF_EXTRACTION_COPY = {
  tr: {
    title: 'PDF İşleme Motoru',
    subtitle: 'OpenDataLoader extraction ve hibrit kontrolü',
    local: 'Yerel',
    hybrid: 'Hibrit',
    bootstrap: 'Runtime kur',
    bootstrapping: 'Runtime kuruluyor...',
    refresh: 'Durumu yenile',
    startHybrid: 'Hibrit başlat',
    stopHybrid: 'Hibrit durdur',
    status: 'Durum',
    options: 'Extraction ayarları',
    advanced: 'Hibrit zenginleştirme',
    structTree: 'Yapı ağacını kullan',
    sanitize: 'Veri temizleme',
    lineBreaks: 'Satır kırılımlarını koru',
    headerFooter: 'Header/footer dahil et',
    strikethrough: 'Strikethrough tespiti',
    formula: 'Formül zenginleştirme',
    picture: 'Görsel/açıklama zenginleştirme',
    ocr: 'OCR zorla',
    tableMethod: 'Tablo yöntemi',
    readingOrder: 'Okuma sırası',
    pageRange: 'Sayfa aralığı',
    hybridMode: 'Hibrit triage',
    hybridTimeout: 'Hibrit zaman aşımı (ms)',
    ocrLang: 'OCR dili',
    ocrLangCustomHint: 'Virgülle ayırarak birden fazla kod (ör. ko,en). Boş bırakırsanız sunucuya dil iletilmez.',
    port: 'Port',
    imageOutput: 'Görsel çıkışı',
    imageFormat: 'Görsel formatı',
    runtimeReady: 'Runtime hazır',
    runtimeMissing: 'Runtime hazır değil',
    runtimeInstalling: 'Runtime kuruluyor',
    helpAria: 'PDF işleme terimleri yardımı',
    hybridFallback: 'Hybrid fallback',
  },
  en: {
    title: 'PDF Engine',
    subtitle: 'OpenDataLoader extraction and hybrid control',
    local: 'Local',
    hybrid: 'Hybrid',
    bootstrap: 'Bootstrap runtime',
    bootstrapping: 'Bootstrapping runtime...',
    refresh: 'Refresh status',
    startHybrid: 'Start hybrid',
    stopHybrid: 'Stop hybrid',
    status: 'Status',
    options: 'Extraction options',
    advanced: 'Hybrid enrichment',
    structTree: 'Use struct tree',
    sanitize: 'Sanitize sensitive data',
    lineBreaks: 'Keep line breaks',
    headerFooter: 'Include header/footer',
    strikethrough: 'Detect strikethrough',
    formula: 'Formula enrichment',
    picture: 'Picture/chart enrichment',
    ocr: 'Force OCR',
    tableMethod: 'Table method',
    readingOrder: 'Reading order',
    pageRange: 'Page range',
    hybridMode: 'Hybrid triage',
    hybridTimeout: 'Hybrid timeout (ms)',
    ocrLang: 'OCR language',
    ocrLangCustomHint:
      'Comma-separated codes for multiple languages (e.g. ko,en). Leave empty to omit --ocr-lang.',
    port: 'Port',
    imageOutput: 'Image output',
    imageFormat: 'Image format',
    runtimeReady: 'Runtime ready',
    runtimeMissing: 'Runtime not ready',
    runtimeInstalling: 'Runtime is installing',
    helpAria: 'PDF processing terms help',
    hybridFallback: 'Hybrid fallback',
  },
} as const;

export type PdfExtractionCopy = (typeof PDF_EXTRACTION_COPY)[LanguageCode];
